### ISSUE TITLE
usage / API in README.md?

### ISSUE THREAD

**Issue by guruthree** [pimoroni/trilobot-python#30]
I was trying to find out what functionality the library provided, but was unable to do so easily.

I checked the [root directory README](https://github.com/pimoroni/trilobot-python/blob/main/README.md) and only found installation directions. I had to manually navigate every folder until I finally found https://github.com/pimoroni/trilobot-python/blob/main/library/trilobot/README.md which had the information I was looking for. I suggest adding at least a Usage section to the root directory README that either links to the useful readme or to demos or something. A usage section for https://github.com/pimoroni/trilobot-python/blob/main/library/README.md would probably also be helpful.

**Comment by ZodiusInfuser** [comment]
Thanks for the suggestion. I have now added links to the examples and usage readme's in the two places you highlighted.
