### ISSUE TITLE
Add support for Xbox One Wireless Controller 

### ISSUE THREAD

**Issue by Jenson7987** [pimoroni/trilobot-python#34]
Hi,

I have created and tested a patch to add a controller definition for the Xbox One Wireless Controller which is different to the Xbox 360 Wireless Controller.

[xbox_one_controller_patch.txt](https://github.com/pimoroni/trilobot-python/files/9447458/xbox_one_controller_patch.txt)

Please let me know if you need any further information.

Kind regards,
Jenson

**Comment by ZodiusInfuser** [comment]
Hey Jenson! Thanks for this, and apologies for not seeing it until now. I do not have an Xbox One controller to test with, but your config looks sensible. I will get it raised as a PR and merged.

**Comment by ZodiusInfuser** [comment]
This is now in the latest release. Thanks for the contribution!
